### ISSUE TITLE
Default timeout bug

### ISSUE THREAD

**Issue by michalzielanski** [phpinnacle/ridge#17]
In the configuration, the default timeout is written as milliseconds:
https://github.com/phpinnacle/ridge/blob/adcced8abecc26ec26c407fb18e3ef59bcb06594/src/Config.php#L25-L26
and in the client it is additionally multiplied by 1000:
https://github.com/phpinnacle/ridge/blob/adcced8abecc26ec26c407fb18e3ef59bcb06594/src/Client.php#L103
Timeout in configuration should be in seconds or milliseconds?

**Comment by mmasiukevich** [comment]
It was fixed a long time ago
